import Footer from '@/components/Footer'
import NavBar from '@/components/NavBar'
import './globals.css'
import type { Metadata } from 'next'
import { Montserrat, Montserrat_Subrayada } from 'next/font/google'
// import localFont from 'next/font/local'

const inter = Montserrat(
  {
    weight: ["400", "100", "200"],
    subsets: ["latin",],
  })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const TestCom: React.FC = () => {
  return (
    <div>
      <h1 className='font-thin'>Test</h1>
    </div>
  )
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <TestCom />
        <NavBar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
